import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        chrome: 'readonly',
        window: 'writable',
        document: 'writable',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        MutationObserver: 'readonly',
        Node: 'readonly',
        HTMLElement: 'readonly',
        Element: 'readonly',
        Event: 'readonly',
        MouseEvent: 'readonly',
        InputEvent: 'readonly',
        KeyboardEvent: 'readonly',
        FocusEvent: 'readonly',
        Promise: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        Date: 'readonly',
        JSON: 'readonly',
        Object: 'readonly',
        Array: 'readonly',
        String: 'readonly',
        Number: 'readonly',
        Math: 'readonly',
        parseInt: 'readonly',
        parseFloat: 'readonly',
        isNaN: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        fetch: 'readonly',
        WebSocket: 'readonly',
        XMLHttpRequest: 'readonly',
        FormData: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        history: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        crypto: 'readonly',
        performance: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        encodeURIComponent: 'readonly',
        decodeURIComponent: 'readonly',
        getComputedStyle: 'readonly',
        matchMedia: 'readonly',
        ResizeObserver: 'readonly',
        IntersectionObserver: 'readonly',
        AbortController: 'readonly',
        structuredClone: 'readonly',
        CSS: 'readonly',
        PointerEvent: 'readonly',
        DataTransfer: 'readonly',
        NodeFilter: 'readonly',
        XPathResult: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLTextAreaElement: 'readonly',
        CKEDITOR: 'readonly',
        tinymce: 'readonly',
        HTMLSelectElement: 'readonly',
        Proxy: 'readonly',
        WeakMap: 'readonly',
        WeakSet: 'readonly',
        ClipboardEvent: 'readonly',
        DragEvent: 'readonly',
        DOMParser: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
      'no-empty': 'off',
      'no-prototype-builtins': 'off',
    },
  },
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      'tests/**',
      'coverage/**',
      'marked.min.js',
      'scripts/**',
      '.claude/**',
    ],
  },
  // popup-full.js loads popup-modules/* which define these as globals
  // Both popup-full.js and popup-modules/*.js share the same global scope
  {
    files: ['popup-full.js', 'popup-modules/**/*.js'],
    languageOptions: {
      globals: {
        initPopupState: 'readonly',
        loadThemePreference: 'readonly',
        loadSettings: 'readonly',
        loadApprovalMode: 'readonly',
        loadChatHistory: 'readonly',
        setupVoiceInput: 'readonly',
        setupApprovalModeToggle: 'readonly',
        showTemplatesPanel: 'readonly',
        hideTemplatesPanel: 'readonly',
        closeCommandPalette: 'readonly',
        closeReportModal: 'readonly',
        showToast: 'readonly',
        escapeHtml: 'readonly',
        sanitizeHtml: 'readonly',
        getState: 'readonly',
        marked: 'readonly',
        sendGoal: 'readonly',
        Helpers: 'readonly',
        relativeTime: 'readonly',
        formatDuration: 'readonly',
        formatCountdown: 'readonly',
        settingsModal: 'readonly',
        settingsBtn: 'readonly',
        themeModal: 'readonly',
        toggleTheme: 'readonly',
        loadTemplates: 'readonly',
        exportFormatSelect: 'readonly',
        isValidUrl: 'readonly',
        executeCommand: 'readonly',
        getErrorMessage: 'readonly',
      },
    },
  },
];
