// tests/platform-registry.test.js
// Guards background/platforms/index.js, which is generated by
// scripts/generate-platform-registry.cjs from the profiles on disk.
//
// The registry used to be maintained by hand: adding a platform meant editing an
// import, an array entry, and keeping the array sorted by specificity. A missed
// edit produced a profile that existed but never matched anything, and a
// mis-sorted one let a catch-all swallow a specific platform. These tests pin
// both properties.

import { execFileSync } from 'child_process';
import { readdirSync, readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

import { getPlatformProfile, listAllProfiles, findMismatchHints } from '../background/platforms/index.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const PLATFORMS_DIR = path.join(ROOT, 'background', 'platforms');

const profileFiles = readdirSync(PLATFORMS_DIR).filter(f => f.endsWith('.js') && f !== 'index.js');

describe('platform registry generation', () => {
  it('is in sync with the profiles on disk', () => {
    // Fails if someone edits index.js by hand or adds a profile without regenerating.
    expect(() => {
      execFileSync('node', [path.join('scripts', 'generate-platform-registry.cjs'), '--check'], {
        cwd: ROOT, stdio: 'pipe',
      });
    }).not.toThrow();
  });

  it('registers every profile file', () => {
    expect(listAllProfiles()).toHaveLength(profileFiles.length);
  });

  it('gives every profile an id, a label and a memory key prefix', () => {
    for (const p of listAllProfiles()) {
      expect(typeof p.id).toBe('string');
      expect(p.id.length).toBeGreaterThan(0);
      expect(typeof p.label).toBe('string');
      expect(typeof p.memoryKeyPrefix).toBe('string');
    }
  });

  it('has no duplicate ids', () => {
    const ids = listAllProfiles().map(p => p.id);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it('declares a numeric priority in every profile source', () => {
    for (const file of profileFiles) {
      const source = readFileSync(path.join(PLATFORMS_DIR, file), 'utf8');
      expect(source).toMatch(/^\s*priority:\s*\d+/m);
    }
  });
});

describe('registry match order', () => {
  // Order is behaviour: getPlatformProfile returns the FIRST detect() that matches.
  const ids = () => listAllProfiles().map(p => p.id);

  it('keeps the goal-keyword catch-all last', () => {
    expect(ids()[ids().length - 1]).toBe('network_device');
  });

  it('matches the specific SonicWall profile before the on-box fallback', () => {
    const order = ids();
    expect(order.indexOf('sonicwall_nsm')).toBeLessThan(order.indexOf('sonicwall_onbox'));
  });

  it('preserves the order the hand-maintained registry had', () => {
    // Pinned so a priority edit that reshuffles matching is a visible test failure
    // rather than a silent behaviour change. autotask and freshservice were added
    // after the generator landed; every other position is unchanged from the
    // hand-maintained list.
    expect(ids()).toEqual([
      'sonicwall_nsm', 'sonicwall_onbox', 'm365_admin', 'teams_admin', 'fortigate',
      'itglue', 'aruba', 'ambio_viewlinc', 'screenconnect', 'ninjarmm',
      'connectwise_manage', 'autotask', 'datto_rmm', 'cisco', 'paloalto', 'sentinelone',
      'nvd', 'virustotal', 'huntress', 'freshservice', 'network_device',
    ]);
  });
});

describe('newly added profiles', () => {
  describe('autotask', () => {
    it.each([
      'https://ww1.autotask.net/Mvc/ServiceDesk/TicketDetail.mvc?ticketID=12345',
      'https://ww14.autotask.net/Autotask/views/CRM/AccountSearch.aspx',
    ])('detects the regional pod host %s', url => {
      expect(getPlatformProfile(url, '').id).toBe('autotask');
    });

    it('detects from the goal when the url is unrelated', () => {
      expect(getPlatformProfile('https://example.com/', 'open the Autotask ticket for Contoso').id).toBe('autotask');
    });

    it('does not claim an unrelated host', () => {
      expect(getPlatformProfile('https://autotask.example.com/', 'buy milk')).toBeNull();
    });
  });

  describe('freshservice', () => {
    it.each([
      'https://contoso.freshservice.com/a/tickets/4521',
      'https://acme.freshservice.com/a/assets',
    ])('detects the tenant subdomain %s', url => {
      expect(getPlatformProfile(url, '').id).toBe('freshservice');
    });

    it('detects from the goal when the url is unrelated', () => {
      expect(getPlatformProfile('https://example.com/', 'check freshservice SLA breaches').id).toBe('freshservice');
    });

    it('does not claim a lookalike host', () => {
      expect(getPlatformProfile('https://freshservice.com.evil.test/', 'buy milk')).toBeNull();
    });
  });

  it('gives both profiles the fields the prompt layer reads', () => {
    for (const id of ['autotask', 'freshservice']) {
      const p = getPlatformProfile('', id === 'autotask' ? 'autotask thing' : 'freshservice thing');
      expect(p.id).toBe(id);
      expect(Array.isArray(p.pageTypes)).toBe(true);
      expect(p.pageTypes.length).toBeGreaterThan(0);
      expect(Array.isArray(p.workflowHints)).toBe(true);
      expect(Array.isArray(p.knownGotchas)).toBe(true);
      expect(typeof p.commitFlow).toBe('string');
      for (const pt of p.pageTypes) {
        expect(pt.urlMatch instanceof RegExp).toBe(true);
        expect(typeof pt.hint).toBe('string');
      }
      for (const wh of p.workflowHints) {
        expect(wh.match instanceof RegExp).toBe(true);
        expect(typeof wh.hint).toBe('string');
      }
    }
  });
});

describe('getPlatformProfile', () => {
  it('returns null when nothing matches', () => {
    expect(getPlatformProfile('https://example.com/', 'buy milk')).toBeNull();
  });

  it('tolerates a null url and goal', () => {
    expect(() => getPlatformProfile(null, null)).not.toThrow();
  });

  it('resolves a known platform from its url', () => {
    const profile = getPlatformProfile('https://my.connectwise.com/ServiceDesk/Tickets/123', '');
    expect(profile && profile.id).toBe('connectwise_manage');
  });

  it('survives a profile whose detect() throws', () => {
    // getPlatformProfile catches per-profile errors and continues; assert that a
    // malformed url cannot take the whole lookup down.
    expect(() => getPlatformProfile('not-a-url', 'anything')).not.toThrow();
  });
});

describe('findMismatchHints', () => {
  it('returns an empty array for a profile without hints', () => {
    expect(findMismatchHints({}, 'some goal')).toEqual([]);
  });

  it('returns an empty array when goal is missing', () => {
    expect(findMismatchHints({ mismatchHints: [{ pattern: /x/, onbox: 'a', nsm: 'b' }] }, '')).toEqual([]);
  });

  it('maps a matching on-box path to its cloud equivalent', () => {
    const profile = { mismatchHints: [{ pattern: /firewall settings/i, onbox: 'Manage > Firewall', nsm: 'NSM > Policies' }] };
    expect(findMismatchHints(profile, 'open firewall settings')).toEqual([{ onbox: 'Manage > Firewall', target: 'NSM > Policies' }]);
  });

  it('skips a hint whose pattern throws', () => {
    const bad = { mismatchHints: [{ pattern: { test() { throw new Error('bad'); } }, onbox: 'a', nsm: 'b' }] };
    expect(() => findMismatchHints(bad, 'goal')).not.toThrow();
    expect(findMismatchHints(bad, 'goal')).toEqual([]);
  });
});
